### ISSUE TITLE
The effects here on this handwriting is really amazing

### ISSUE THREAD

**Issue by jboarman** [sherlockdoyle/Handwriter#1]
Would you be interested in collaborating on similar work with [The Augraphy Project](https://github.com/sparkfish/augraphy/)?

We're working to simulate real-world document distortions, and your work on this handwriter project is a great example of the kinds of distortions that make for realistic renderings for use in machine learning projects that are designed to reverse those real-world distortions.

Even just to consult and share your ideas would be a great resource.  If you are available to be sponsored as a paid contributor, that would be really exciting for us as well.  Please reach out to me to discuss further if you are interested!

**Comment by sherlockdoyle** [comment]
Thanks for reaching out to me about The Augraphy Project. I would be delighted to share my ideas and contribute to the project, as long as it remains open source and I'm given proper credit for my contributions. I'm not looking for payment at this time, but I appreciate your offer.

Please let me know more about the project and how I can contribute. I'm looking forward to working with you!

**Comment by jboarman** [comment]
Definitely!  We meet on slack and zoom if you'd like to join in that conversation.  I can invite you via email.  You can find my email in my GitHub profile.
